name: Prek

on:
    workflow_call:
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    prek:
        name: Prek
        runs-on: ubuntu-latest

        steps:
            - name: Update Rust
              run: rustup update stable
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Use dependencies cache
              uses: actions/cache@v5
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-
            - name: Install cargo-deny
              uses: taiki-e/install-action@cargo-deny
            - name: Install cargo-machete
              uses: taiki-e/install-action@cargo-machete
            - name: Install cargo-sort
              uses: taiki-e/install-action@cargo-sort
            - name: Run Prek
              uses: j178/prek-action@v2
              with:
                  extra-args: "--all-files --skip sqlx-prepare-check"
